apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
roleRef:
  kind: Role
  name: read-only #The role name you defined in the Role configuration


  apiGroup: rbac.authorization.k8s.io
subjects:
– kind: User
  name: john #The name of the user to give the role to


  apiGroup: rbac.authorization.k8s.io
